document.documentElement.classList.add('v312');
const polish=document.createElement('link');polish.rel='stylesheet';polish.href='v312-polish.css?v=312';document.head.appendChild(polish);
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const lerp=(a,b,t)=>a+(b-a)*t;
const scenes=$$('.scene');const rail=$('.progress-rail');if(rail){rail.innerHTML=scenes.map(()=>'<i></i>').join('')}const railDots=rail?$$('i',rail):[];
let vh=innerHeight,vw=innerWidth,py=scrollY,lastY=scrollY,velocity=0,pointer={x:0,y:0},smoothPointer={x:0,y:0};
function resize(){vh=innerHeight;vw=innerWidth}addEventListener('resize',resize,{passive:true});addEventListener('pointermove',e=>{pointer.x=(e.clientX/vw-.5)*2;pointer.y=(e.clientY/vh-.5)*2},{passive:true});addEventListener('pointerleave',()=>{pointer.x=0;pointer.y=0});
const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-in');revealObserver.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -7% 0px'});$$('[data-reveal]').forEach(el=>revealObserver.observe(el));
function sceneProgress(s){const r=s.getBoundingClientRect();return clamp((vh-r.top)/(vh+r.height))}function activeScene(){let best={i:0,score:-1};scenes.forEach((s,i)=>{const r=s.getBoundingClientRect();const visible=Math.max(0,Math.min(r.bottom,vh)-Math.max(r.top,0));const score=visible/Math.min(vh,r.height);if(score>best.score)best={i,score}});return best.i}
const object=$('.movx-chassis');const crt=$('.crt');const tunnel=$('.tunnel-stage');const tunnelFrames=tunnel?$$('.tunnel-frame',tunnel):[];const portalX=$('.portal-x');const studio=$('.studio-stage');const wall=studio?$('.studio-wall',studio):null;const contactWindow=$('.contact-window');const projectPanels=$$('.project-panel');const consoleUnits=$$('.console-unit');const floats=$$('.float');const topMeta=$('.top-meta');
const sceneLabels=['BOOT / DEVICE','HERO / OBJECT','ENTER THE X','WORK / ARCHIVE','CREATIVE MACHINE','ZERO GRAVITY','SPATIAL STUDIO','PEOPLE / ABOUT','CONTACT / EXIT'];
function frame(t){const y=scrollY;const dy=y-lastY;lastY=y;velocity=lerp(velocity,dy,.08);py=lerp(py,y,.11);smoothPointer.x=lerp(smoothPointer.x,pointer.x,.065);smoothPointer.y=lerp(smoothPointer.y,pointer.y,.065);document.documentElement.style.setProperty('--mx',smoothPointer.x.toFixed(3));document.documentElement.style.setProperty('--my',smoothPointer.y.toFixed(3));document.documentElement.style.setProperty('--sv',clamp(velocity/40,-1,1).toFixed(3));
 const active=activeScene();scenes.forEach((s,i)=>{const p=sceneProgress(s);s.style.setProperty('--sp',p.toFixed(4));s.classList.toggle('is-active',i===active)});railDots.forEach((d,i)=>d.classList.toggle('on',i===active));if(topMeta)topMeta.textContent=`${String(active+1).padStart(2,'0')} / ${sceneLabels[active]||'MOVX'}  ·  Y2K SPATIAL CREATIVE PLAYGROUND`;
 if(crt){const s=$('#boot');const p=s?sceneProgress(s):0;crt.style.transform=`perspective(1300px) rotateY(${-7+smoothPointer.x*2.1+(p-.5)*1.4}deg) rotateX(${2-smoothPointer.y*1.3}deg) translate3d(${smoothPointer.x*5}px,${smoothPointer.y*4}px,0)`}
 if(object){const s=$('#hero');const p=s?sceneProgress(s):0;object.style.transform=`rotateY(${-10+smoothPointer.x*4+(p-.5)*4}deg) rotateX(${4-smoothPointer.y*3}deg) translate3d(${smoothPointer.x*11}px,${(p-.5)*-18+smoothPointer.y*7}px,0) scale(${.985+p*.025})`}
 if(tunnel){const s=$('#portal');const p=s?sceneProgress(s):0;tunnelFrames.forEach((f,i)=>{const depth=(i+1)*(16+26*p);const drift=smoothPointer.x*(i+1)*2;f.style.transform=`translate(calc(-50% + ${drift}px),-50%) scale(${1+depth/430})`});if(portalX)portalX.style.transform=`translate(-50%,-50%) scale(${.88+p*.24}) rotate(${(p-.5)*1.2}deg)`}
 if(projectPanels.length){const s=$('#work');const p=s?sceneProgress(s):0;const base=[[-110,24,-.9],[-10,12,-.45],[100,0,0],[-8,-13,.45],[-110,-25,.9]];projectPanels.forEach((el,i)=>{if(el.matches(':hover'))return;const b=base[i]||[0,0,0];const focus=1-Math.min(1,Math.abs((i/(projectPanels.length-1||1))-p)*1.45);const vx=clamp(velocity,-18,18)*(i-2)*.12;el.style.transform=`translate3d(${vx}px,${(1-focus)*10}px,${b[0]+focus*70}px) rotateY(${b[1]*(1-focus*.5)}deg) scale(${.9+focus*.13})`;el.style.opacity=`${.58+focus*.42}`;el.style.filter=`brightness(${.76+focus*.24})`})}
 if(consoleUnits.length){const s=$('#machine');const p=s?sceneProgress(s):0;const idx=Math.min(consoleUnits.length-1,Math.floor(clamp((p-.15)/.68)*consoleUnits.length));consoleUnits.forEach((u,i)=>{u.classList.toggle('active',i===idx);u.style.transform=`translateY(${i===idx?-7:0}px) scale(${i===idx?1.018:1})`;u.style.boxShadow=i===idx?'inset 0 0 0 1px rgba(255,255,255,.78),0 26px 42px rgba(50,44,38,.14),0 0 0 1px rgba(255,91,27,.24)':'inset 0 0 0 1px rgba(255,255,255,.7),0 9px 18px rgba(50,44,38,.06)'})}
 floats.forEach((el,i)=>{if(el.classList.contains('dragging')||el.dataset.dragged==='1')return;const a=t*.00045+i*1.19;const bob=Math.sin(a)*7;const sway=Math.cos(a*.77)*5;el.style.transform=`translate3d(${sway+smoothPointer.x*(i%2?4:-4)}px,${bob+smoothPointer.y*(i%3?3:-3)}px,0) rotate(${Math.sin(a*.6)*2.2}deg)`});
 if(studio&&wall){const s=$('#studio');const p=s?sceneProgress(s):0;wall.style.transform=`translate3d(${smoothPointer.x*5}px,${(p-.5)*-22+smoothPointer.y*4}px,${p*22}px) scale(${1+p*.018})`}
 if(contactWindow){const s=$('#contact');const p=s?sceneProgress(s):0;contactWindow.style.transform=`translate3d(${smoothPointer.x*5}px,${(p-.5)*-18+smoothPointer.y*4}px,0) rotateY(${smoothPointer.x*-1.2}deg)`}
 requestAnimationFrame(frame)}requestAnimationFrame(frame);
floats.forEach(el=>{let drag=false,ox=0,oy=0;el.addEventListener('pointerdown',e=>{drag=true;el.dataset.dragged='1';el.classList.add('dragging');const r=el.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;el.style.transform='none';el.setPointerCapture?.(e.pointerId)});el.addEventListener('pointermove',e=>{if(!drag)return;const zone=el.parentElement.getBoundingClientRect();const x=clamp(e.clientX-zone.left-ox,0,zone.width-el.offsetWidth);const y=clamp(e.clientY-zone.top-oy,0,zone.height-el.offsetHeight);el.style.left=`${x}px`;el.style.top=`${y}px`});const up=e=>{drag=false;el.classList.remove('dragging');try{el.releasePointerCapture?.(e.pointerId)}catch{}};el.addEventListener('pointerup',up);el.addEventListener('pointercancel',up)});
const bootBar=$('[data-boot-load]');if(bootBar){bootBar.style.width='0';setTimeout(()=>bootBar.style.width='100%',220)}const power=$('[data-power]');if(power){power.addEventListener('click',()=>document.querySelector('#hero')?.scrollIntoView({behavior:'smooth'}))}
if(matchMedia('(prefers-reduced-motion: reduce)').matches){$$('[data-reveal]').forEach(el=>el.classList.add('is-in'))}
