const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));const lerp=(a,b,t)=>a+(b-a)*t;const ease=t=>1-Math.pow(1-clamp(t),3);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const ROOT='https://videoia070707-design.github.io/Portifolio/';
const projects=[
{slug:'hardwork-thermo-plus',client:'Hardwork',title:'Thermo+ Product Campaign',featured:true,featuredOrder:1,cover:'assets/projects/hardwork-thermo-plus/hardwork-thermo-plus-01.webp',tags:['Product','3D'],artworkCount:6},
{slug:'voltara-operacoes',client:'Voltara Energia',title:'Operações de Alto Desempenho',featured:true,featuredOrder:2,cover:'assets/projects/voltara-operacoes/slide-01.webp',tags:['B2B','Energy'],artworkCount:6},
{slug:'belive-cashflow',client:'Belive',title:'Cashflow Intelligence',featured:true,featuredOrder:3,cover:'assets/projects/belive-cashflow.webp',tags:['3D','Finance'],artworkCount:6},
{slug:'motionhub',client:'MotionHub',title:'Product Storytelling',featured:true,featuredOrder:4,cover:'assets/projects/motionhub-01.webp',tags:['SaaS','Product'],artworkCount:6},
{slug:'marina-gengival',client:'Dra. Marina Alves',title:'Sorriso Gengival',featured:true,featuredOrder:5,cover:'assets/projects/marina-gengival/01.webp',tags:['Healthcare','Carousel'],artworkCount:5},
{slug:'hardwork-modo',client:'Hardwork',title:'Modo Hardwork',featured:true,featuredOrder:6,cover:'assets/projects/hardwork-modo/hardwork-modo-01.webp',tags:['Character','Campaign'],artworkCount:7},
{slug:'marina-familia',client:'Dra. Marina Alves',title:'Cuidar Cedo',cover:'assets/projects/marina-familia/01.webp',tags:['Family Care'],artworkCount:3},
{slug:'voltara-vantagem',client:'Voltara Energia',title:'Vantagem Operacional',cover:'assets/projects/voltara-vantagem/slide-01.webp',tags:['B2B'],artworkCount:6},
{slug:'voltara-viabilidade',client:'Voltara Energia',title:'Viabilidade Solar',cover:'assets/projects/voltara-viabilidade/voltara-viabilidade-01.webp',tags:['Energy'],artworkCount:6},
{slug:'voltara-confianca-escala',client:'Voltara Energia',title:'Confiança & Escala',cover:'assets/projects/voltara-confianca-escala/slide-01.webp',tags:['Brand System'],artworkCount:6},
{slug:'voltara-engenharia-aplicada',client:'Voltara Energia',title:'Engenharia Aplicada',cover:'assets/projects/voltara-engenharia-aplicada/slide-01.webp',tags:['Industrial'],artworkCount:4},
{slug:'voltara-infraestrutura',client:'Voltara Energia',title:'Infraestrutura Solar Corporativa',cover:'assets/projects/voltara-infraestrutura/slide-01.webp',tags:['Corporate'],artworkCount:3},
{slug:'hardwork-neon-direction',client:'Hardwork',title:'Neon Direction',cover:'assets/projects/hardwork-neon-direction/slide-01.webp',tags:['Campaign'],artworkCount:3}
];
const state={scroll:scrollY,smooth:scrollY,velocity:0,last:scrollY,pointer:{x:0,y:0,tx:0,ty:0},active:null,local:0,vw:innerWidth,vh:innerHeight,time:0};const scenes=[];let work={el:null,track:null,max:0,start:0,range:1};
function boot(){const bar=$('[data-boot-bar]');const status=$('[data-boot-status]');let p=0;const labels=['SYNC / TYPE','SYNC / MOTION','SYNC / PROJECTS','SYSTEM / READY'];const tick=()=>{p=Math.min(1,p+.05+Math.random()*.025);if(bar)bar.style.width=`${p*100}%`;if(status)status.textContent=labels[Math.min(labels.length-1,Math.floor(p*labels.length))];if(p<1)setTimeout(tick,95);else setTimeout(()=>$('.boot')?.classList.add('done'),520)};tick()}
function coverFor(p){return ROOT+p.cover}
function renderWork(){const track=$('[data-work-track]');if(!track)return;const featured=projects.filter(p=>p.featured).sort((a,b)=>(a.featuredOrder||99)-(b.featuredOrder||99));track.innerHTML=featured.map((p,i)=>`<article class="work-card" data-project="${p.slug}"><img alt="${p.title}" loading="${i<2?'eager':'lazy'}" src="${coverFor(p)}"><div class="work-card__overlay"><div><span>${String(i+1).padStart(2,'0')} / ${p.client}</span><h3>${p.title}</h3></div><span>${p.tags?.slice(0,2).join(' / ')||''}</span></div></article>`).join('');work.el=$('.work-journey');work.track=track;measureWork()}
function renderArchive(){const grid=$('[data-archive-grid]');if(!grid)return;grid.innerHTML=projects.map(p=>`<article class="archive-item"><img alt="${p.title}" loading="lazy" src="${coverFor(p)}"><h3>${p.title}</h3><p>${p.client} · ${p.artworkCount||0} peças</p></article>`).join('')}
function setupArchive(){const drawer=$('[data-archive]');$$('[data-open-archive]').forEach(b=>b.addEventListener('click',()=>drawer?.classList.add('open')));$('[data-close-archive]')?.addEventListener('click',()=>drawer?.classList.remove('open'));addEventListener('keydown',e=>{if(e.key==='Escape')drawer?.classList.remove('open')})}
function setupTitles(){$$('.fx-title').forEach((el,idx)=>{el.dataset.fxIndex=idx;$$('.fx-line>span',el).forEach((line,i)=>line.dataset.line=i)})}
function titleProgress(el){const r=el.getBoundingClientRect();return clamp((state.vh*.9-r.top)/(state.vh*1.02))}
function applyTitle(el,p){if(reduced){$$('.fx-line>span',el).forEach(x=>{x.style.cssText='opacity:1;transform:none;filter:none;clip-path:none'});return}const type=el.dataset.fx||'clip';const lines=$$('.fx-line>span',el);if(type==='decode'){lines.forEach((l,i)=>{const q=ease(clamp((p-i*.07)/.86));l.style.opacity=q;l.style.filter=`blur(${lerp(12,0,q)}px)`;l.style.transform=`translate3d(0,${lerp(72,0,q)}px,0) scale(${lerp(.94,1,q)})`;l.style.letterSpacing=`${lerp(.05,-.08,q)}em`})}if(type==='clip'){lines.forEach((l,i)=>{const q=ease(clamp((p-i*.08)/.84));l.style.opacity=q;l.style.transform=`translate3d(${lerp(i%2?-6:8,0,q)}vw,0,0)`;l.style.clipPath=`inset(0 ${lerp(100,0,q)}% 0 0)`})}if(type==='assemble'){const d=[-1,1,-.6];lines.forEach((l,i)=>{const q=ease(clamp((p-i*.065)/.84));l.style.opacity=q;l.style.transform=`translate3d(${lerp((d[i]||1)*13,0,q)}vw,${lerp(38,0,q)}px,0) rotate(${lerp((d[i]||1)*2.5,0,q)}deg)`;l.style.clipPath=`inset(${lerp(45,0,q)}% 0 ${lerp(45,0,q)}% 0)`})}if(type==='depth'){lines.forEach((l,i)=>{const q=ease(clamp((p-i*.075)/.86));l.style.opacity=q;l.style.filter=`blur(${lerp(9,0,q)}px)`;l.style.transformOrigin='0 50%';l.style.transform=`perspective(900px) rotateX(${lerp(-54,0,q)}deg) translate3d(0,${lerp(78,0,q)}px,0)`})}if(type==='shutter'){lines.forEach((l,i)=>{const q=ease(clamp((p-i*.08)/.9));l.style.opacity=lerp(.1,1,q);l.style.clipPath=`inset(${lerp(49,0,q)}% 0 ${lerp(49,0,q)}% 0)`;l.style.transform=`translate3d(${lerp(i===1?5:-3,0,q)}vw,0,0)`})}if(type==='track'){lines.forEach((l,i)=>{const q=ease(clamp((p-i*.07)/.9));l.style.opacity=q;l.style.letterSpacing=`${lerp(.23,-.08,q)}em`;l.style.transform=`translate3d(${lerp(7,0,q)}vw,0,0)`})}}
function setupCopy(){$$('.scene').forEach(scene=>$$('[data-copy]',scene).forEach((el,i)=>el.dataset.copyIndex=i))}
function updateCopy(){if(reduced)return;$$('[data-copy]').forEach(el=>{const r=el.getBoundingClientRect();const p=ease(clamp((state.vh*.95-r.top)/(state.vh*.68)));el.style.opacity=p;el.style.transform=`translate3d(0,${lerp(36,0,p)}px,0)`})}
function setupScenes(){$$('[data-scene]').forEach((el,i)=>scenes.push({el,id:el.dataset.scene,index:i,top:0,height:1}));const rail=$('[data-rail]');if(rail)rail.innerHTML=scenes.map((s,i)=>`<button aria-label="${s.id}" data-rail-to="${i}"></button>`).join('');$$('[data-rail-to]').forEach(b=>b.addEventListener('click',()=>scenes[+b.dataset.railTo]?.el.scrollIntoView({behavior:'smooth'})))}
function measure(){state.vw=innerWidth;state.vh=innerHeight;scenes.forEach(s=>{s.top=s.el.offsetTop;s.height=Math.max(1,s.el.offsetHeight)});measureWork()}
function measureWork(){if(!work.el||!work.track)return;work.start=work.el.offsetTop;work.range=Math.max(1,work.el.offsetHeight-state.vh);work.max=Math.max(0,work.track.scrollWidth-state.vw)}
function resolveScene(){let best=null;for(const s of scenes){const r=s.el.getBoundingClientRect();const vis=Math.max(0,Math.min(r.bottom,state.vh)-Math.max(r.top,0));const score=vis/Math.min(state.vh,r.height);if(!best||score>best.score)best={s,score,r}}if(!best)return;state.active=best.s.id;state.local=clamp((state.vh*.82-best.r.top)/(state.vh+best.r.height*.55));document.body.dataset.scene=state.active;$$('[data-rail-to]').forEach((b,i)=>b.classList.toggle('active',i===best.s.index));if($('.topbar__mode'))$('.topbar__mode').textContent=`${String(best.s.index+1).padStart(2,'0')} / ${best.s.id.toUpperCase()}`}
function updateWork(){if(!work.el||!work.track)return;const p=clamp((state.smooth-work.start)/work.range);work.track.style.transform=`translate3d(${-p*work.max}px,0,0)`;const cards=$$('.work-card',work.track);let active=null;cards.forEach(card=>{const r=card.getBoundingClientRect();const d=Math.abs(r.left+r.width/2-state.vw/2);if(!active||d<active.d)active={card,d}});cards.forEach(c=>c.classList.toggle('is-muted',active&&c!==active.card))}
function updateHero(){const glyph=$('.soft-glyph');if(!glyph)return;const scene=$('[data-scene="hero"]');const r=scene?.getBoundingClientRect();if(!r)return;const p=clamp(-r.top/(scene.offsetHeight-state.vh));const px=state.pointer.x,py=state.pointer.y;glyph.style.transform=`translate3d(${px*18}px,${py*12+p*18}px,0) rotate(${p*2.2}deg)`;$('.soft-glyph__core').style.transform=`rotate(${p*34+px*9}deg) scale(${1-p*.08})`;$('.soft-glyph__ring').style.transform=`rotate(${(-18+p*55)}deg) scale(${1+p*.08})`;$('.soft-glyph__pill').style.transform=`translate3d(${p*25}px,${-p*42}px,0) rotate(${18-p*25}deg)`;$('.soft-glyph__tile').style.transform=`translate3d(${-p*34}px,${p*24}px,0) rotate(${-p*10}deg)`}
function updatePosition(){const scene=$('[data-scene="position"]');if(!scene)return;const r=scene.getBoundingClientRect();const p=clamp((state.vh-r.top)/(state.vh+r.height*.65));$$('.position__words .word').forEach((w,i)=>{const dir=[-1,.4,1][i];w.style.transform=`translate3d(${lerp(dir*11,0,ease(p))}vw,0,0)`;w.style.opacity=lerp(.18,1,ease(p))})}
function updateConsole(){const c=$('.console');if(!c)return;const scene=$('[data-scene="capabilities"]');const r=scene?.getBoundingClientRect();if(!r)return;const p=clamp((state.vh-r.top)/(state.vh+r.height*.75));const px=state.pointer.x,py=state.pointer.y;c.style.transform=state.vw<900?'none':`perspective(1100px) rotateX(${lerp(16,8,p)-py*2.5}deg) rotateY(${lerp(-12,-4,p)+px*3}deg) translateY(${lerp(45,0,p)}px)`}
function updateStudio(){const scene=$('[data-scene="studio"]');if(!scene)return;const r=scene.getBoundingClientRect();const p=clamp(-r.top/(scene.offsetHeight-state.vh));const screen=$('.room__screen');const a=$('.room__wall.a'),b=$('.room__wall.b');if(screen)screen.style.transform=`translate3d(${lerp(60,-10,p)}px,${lerp(80,-20,p)}px,80px) scale(${lerp(.88,1.04,p)})`;if(a)a.style.transform=`rotateY(${18-p*8}deg) translateX(${p*-24}px)`;if(b)b.style.transform=`rotateY(${-15+p*6}deg) translateX(${p*26}px)`}
function setupModules(){const modules=$$('.module');const title=$('[data-cap-title]'),body=$('[data-cap-body]');const data=[['ART DIRECTION','Identidade, campanhas e sistemas visuais com hierarquia clara e presença própria'],['MOTION / VIDEO','Ritmo, edição e movimento pensados como parte da linguagem, não como acabamento'],['AI CREATIVE','Imagem, vídeo e pipelines de AI usados como ferramenta de direção e produção'],['UI / INTERACTIVE','Interfaces e experiências digitais onde layout, movimento e interação trabalham juntos']];modules.forEach((m,i)=>{const activate=()=>{modules.forEach(x=>x.classList.remove('active'));m.classList.add('active');if(title)title.textContent=data[i][0];if(body)body.textContent=data[i][1]};m.addEventListener('mouseenter',activate);m.addEventListener('click',activate)})}
function setupToys(){const box=$('.toybox');if(!box)return;$$('.toy',box).forEach(toy=>{let drag=false,ox=0,oy=0;toy.addEventListener('pointerdown',e=>{drag=true;toy.setPointerCapture(e.pointerId);ox=e.clientX-toy.offsetLeft;oy=e.clientY-toy.offsetTop;toy.style.cursor='grabbing'});toy.addEventListener('pointermove',e=>{if(!drag)return;const br=box.getBoundingClientRect();toy.style.left=`${clamp(e.clientX-br.left-ox,0,box.clientWidth-toy.offsetWidth)}px`;toy.style.top=`${clamp(e.clientY-br.top-oy,0,box.clientHeight-toy.offsetHeight)}px`});toy.addEventListener('pointerup',()=>{drag=false;toy.style.cursor='grab'});toy.addEventListener('pointercancel',()=>drag=false)})}
function initToyPositions(){const box=$('.toybox');if(!box)return;const defs=[[.08,.18,140,100],[.33,.08,110,110],[.63,.2,170,92],[.18,.62,120,120],[.55,.62,150,105],[.78,.55,100,100]];$$('.toy',box).forEach((t,i)=>{const d=defs[i%defs.length];t.style.left=`${Math.min(d[0]*box.clientWidth,box.clientWidth-d[2])}px`;t.style.top=`${Math.min(d[1]*box.clientHeight,box.clientHeight-d[3])}px`;t.style.width=`${d[2]}px`;t.style.height=`${d[3]}px`})}
function updatePointer(){state.pointer.x+=(state.pointer.tx-state.pointer.x)*.055;state.pointer.y+=(state.pointer.ty-state.pointer.y)*.055}
function frame(t){state.time=t;state.scroll=scrollY;state.velocity+=(state.scroll-state.last-state.velocity)*.11;state.last=state.scroll;state.smooth+=(state.scroll-state.smooth)*.072;updatePointer();resolveScene();$$('.fx-title').forEach(el=>applyTitle(el,titleProgress(el)));updateCopy();updateHero();updatePosition();updateWork();updateConsole();updateStudio();requestAnimationFrame(frame)}
function init(){document.documentElement.classList.add('motion-ready');boot();setupScenes();setupTitles();setupCopy();setupArchive();setupModules();setupToys();renderWork();renderArchive();measure();setTimeout(initToyPositions,120);addEventListener('resize',()=>{measure();initToyPositions()},{passive:true});addEventListener('pointermove',e=>{state.pointer.tx=e.clientX/state.vw-.5;state.pointer.ty=e.clientY/state.vh-.5},{passive:true});requestAnimationFrame(frame)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();